baseURL = "https://ekunazanu.dev/"
languageCode = "en-in"
title = "ekunazanu"
copyright = "Creative Commons Attribution-ShareAlike 4.0 International License"
disableHugoGeneratorInject = true
pygmentsUseClasses = true
publishDir = "docs"
[author]
name = "Anchit Roy"
email = "me@ekunazanu.dev"
[sitemap]
filename = 'sitemap.xml'
[outputs]
home = ["HTML", "RSS"]
blog = ["HTML", "RSS"]
[outputFormats.RSS]
mediaType = "application/rss+xml"
baseName = "index"
[related]
includeNewer = true
threshold = 0
toLower = false
[[related.indices]]
name = "title"
weight = 100
[[related.indices]]
name = "categories"
weight = 30
[[related.indices]]
name = "tags"
weight = 100
[[related.indices]]
name = "date"
weight = 10
